on: [push, pull_request]
name: Python linting

permissions:
  contents: read

jobs:
  PythonLinting:
    name: Python linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # master
      - name: Konstruktoid Python linting
        uses: konstruktoid/action-pylint@69fe05b547c932527c55490f386af694001fa5a1 # master
