on: [push, pull_request]
name: Python linting

permissions:
  contents: read

jobs:
  PythonLinting:
    name: Python linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # master
      - name: Konstruktoid Python linting
        uses: konstruktoid/action-pylint@19ff6351d2902b45643bc873c2c39c663c878ca3 # master
